<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsUraPlugin>true</IsUraPlugin>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.1.0</Version>

    <PluginInternalName>AIRedirector</PluginInternalName>
    <PluginDisplayName>转发AI的输出到URA里</PluginDisplayName>
    <PluginAuthor>离披</PluginAuthor>
    <PluginDescription>转发AI的输出到URA里，需要修改版的简化过输出的AI</PluginDescription>
    <PluginChangelog>添加种田杯的转发</PluginChangelog>
    <PluginRepositoryUrl>https://github.com/URA-Plugins/AIRedirector</PluginRepositoryUrl>
    <PluginDependencies>LegendScenarioAnalyzer</PluginDependencies>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AIRedirectorSmoke" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.4.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="deps\LegendScenarioAnalyzer\LegendScenarioAnalyzer.csproj"
                      Private="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UmamusumeResponseAnalyzer" Version="2026.9.1" />
  </ItemGroup>

</Project>
